// Generated by scripts/scrape-bio.mjs from https://www.n1motid.is/strakar/bioplan
// Each team's assigned cinema showing at N1 mótið (fixed for the tournament).
export default {
  "film": "Skósveinar og Skrímsli",
  "cinema": "Nýja Bíó (Sambíóin)",
  "url": "https://www.n1motid.is/strakar/bioplan",
  "teams": {
    "Afturelding Aron": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Keflavík 1": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "B",
      "time": "16:30"
    },
    "KA Hans Viktor": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "Breiðablik Ágúst Orri": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Njarðvík Eiður Aron": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "B",
      "time": "16:30"
    },
    "KA Oliver": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "Breiðablik Viktor Karl": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Snæfellsnes Ingvar Freyr": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "B",
      "time": "16:30"
    },
    "Keflavík 2": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "FH Arngrímur Bjartur": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Stjarnan 1": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "B",
      "time": "16:30"
    },
    "KFA Geir": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "FH Tómas Orri": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Stjarnan 2": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "B",
      "time": "16:30"
    },
    "KR 3": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "Fjölnir 1": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Valur 1": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "B",
      "time": "16:30"
    },
    "Njarðvík Oumar Diouck": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "Fjölnir 2": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Þór Aron Birkir": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "B",
      "time": "16:30"
    },
    "Stjarnan 3": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "Fram 1": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Stjarnan 4": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "Fylkir Gummi Tyrfings": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Þróttur R 1": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "Fylkir Orri Segatta": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Þróttur R 2": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "Grótta Tristan Freyr": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Þróttur R 3": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "HK Arnþór Ari": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Þróttur R 4": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "HK Ívar Örn": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Valur 2": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "ÍA Ísak Bergmann": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Víkingur Gylfi Sig": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "KA Grímsi": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Víkingur Stígur Diljan": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "KR 1": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Víkingur Viktor Örlygur": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "KR 2": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "16:00"
    },
    "Völsungur 1": {
      "day": "Miðvikudagur",
      "date": "2026-07-01",
      "salur": "A",
      "time": "18:00"
    },
    "Afturelding Elmar": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Keflavík 3": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "10:30"
    },
    "Afturelding Gunnar": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Breiðablik Höskuldur": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "KFA Patrekur": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "10:30"
    },
    "Breiðablik Arnór Gauti": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Breiðablik Kristófer Ingi": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "KFR Heiðar Óli": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "10:30"
    },
    "Breiðablik Viktor Örn": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Breiðablik Valgeir Valgeirs": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "KR 5": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "10:30"
    },
    "FH Adolf Daði": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "FH Ísak Óli": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "KR 6": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "10:30"
    },
    "FH Grétar Snær": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "FH Kristján Flóki": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Leiknir": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "10:30"
    },
    "Fjölnir 7": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Fjölnir 5": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Njarðvík Freysteinn Ingi": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "10:30"
    },
    "Fjölnir 8": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Fjölnir 6": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Fram 5": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Fylkir Kári Sigfús": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Fylkir Ólafur Kristófer": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Grótta Caden McLagan": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Hamar/Ægir Binni Eyþórs": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Hamar/Ægir Bjarki Rúnar": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "HK Alexander Örn": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Haukar Jón Barðdal": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "ÍA Daníel Ingi": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "HK Tumi Þorvars": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "KR 8": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "ÍBV 3": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Stjarnan 10": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "ÍR 3": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Stjarnan 9": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "KA Biggi Bald": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Þróttur R 9": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "KA Kári Gauta": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "10:00"
    },
    "Valur 5": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "12:00"
    },
    "Breiðablik Kristinn Steindórs": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "12:30"
    },
    "Afturelding Bjartur": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Skallagrímur": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "14:30"
    },
    "ÍBV 1": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "12:30"
    },
    "Afturelding Cogic": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Stjarnan 5": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "14:30"
    },
    "KA Stubbur": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "12:30"
    },
    "Álftanes Ísak Óli": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Stjarnan 6": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "14:30"
    },
    "Selfoss 1": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "12:30"
    },
    "Breiðablik Anton Logi": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Vestri Elmar Atli": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "14:30"
    },
    "Víkingur Gunnar Vatnhamar": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "12:30"
    },
    "Breiðablik Ásgeir Helgi": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Þór Ágúst Hlyns": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "14:30"
    },
    "Víkingur Óskar Bogga": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "12:30"
    },
    "Breiðablik Kristinn Jóns": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Þróttur R 5": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "14:30"
    },
    "Víkingur Valdimar Ingimundar": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "12:30"
    },
    "FH Baldur Kári": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Þróttur R 6": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "14:30"
    },
    "FH Gils Gísla": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Fjölnir 3": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Fram 2": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Fylkir Theodór Ingi": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Grótta Matthías Kjeld": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "HK Karl Ágúst": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "HK Ólafur Örn": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Höttur 1": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "ÍA Stefán Teitur": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "ÍR 1": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "14:00"
    },
    "Afturelding Kooistra": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "KA Arna Sif": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "16:30"
    },
    "Breiðablik Anton Ari": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "KA Dani Djuric": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "16:30"
    },
    "Breiðablik Ívar Örn": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "KA Guðjón Ernir": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "16:30"
    },
    "FH Benni Bæring": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "KF/Dalvík 1": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "16:30"
    },
    "FH Róbert Hugi": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "KFA Bissi": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "16:30"
    },
    "Fjölnir 4": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "KFR Helgi": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "16:30"
    },
    "Fram 3": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "Selfoss 2": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "B",
      "time": "16:30"
    },
    "Fylkir Birkir Eyþórs": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "Hamar/Ægir Stebbi Hannesar": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "Haukar Pablo Punyed": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "HK Tolli": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "Hvöt 1": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "ÍA Hákon Haralds": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "ÍBU Uppsveitir 1": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "ÍBV 2": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "ÍR 2": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "KR 4": {
      "day": "Fimmtudagur",
      "date": "2026-07-02",
      "salur": "A",
      "time": "16:00"
    },
    "KR 7": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "Afturelding Holtan": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "11:30"
    },
    "Fram 4": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Njarðvík Valdimar": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "Álftanes Unnar Ari": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "11:30"
    },
    "Fylkir Benni Daríus": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Samherjar Haaland": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "Breiðablik Andri Yeoman": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "11:30"
    },
    "Grótta Björgvin Brimi": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Samherjar Mbappe": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "Breiðablik Davíð Ingvars": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "11:30"
    },
    "Haukar Einar Karl": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Snæfellsnes Jón Björgvin": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "Breiðablik Óli Valur": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "11:30"
    },
    "HK Magnús Arnar": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Stjarnan 7": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "FH Jökull Andrés": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "11:30"
    },
    "Höttur 2": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Stjarnan 8": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "FH Kjartan Kári": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "11:30"
    },
    "ÍA Arnór Sig": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Valur 4": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "ÍBU Uppsveitir 2": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Vestri Birkir Eydal": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "ÍBV 4": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Vestri Pétur Bjarna": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "ÍR 4": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Víkingur Erlingur Agnars": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "KA Harpa Jó": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Víkingur Ingvar Jóns": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "KA Markús Máni": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Völsungur 2": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "Keflavík 4": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Þór Bjarni Guðjón": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "KF/Dalvík 2": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Þór Christian Jakobsen": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "KFA Þór": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Þróttur R 7": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "KFR Þórður": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "13:00"
    },
    "Þróttur R 8": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "A",
      "time": "11:00"
    },
    "Sindri/Neisti": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "15:45"
    },
    "Valur 3": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "15:45"
    },
    "Víkingur Davíð Atla": {
      "day": "Föstudagur",
      "date": "2026-07-03",
      "salur": "B",
      "time": "15:45"
    }
  }
};
