// Generated by scripts/build-vaktir.mjs from data/*_vaktir.csv (GDPR: first names only).
export default {
  "teams": {
    "Breiðablik Kristófer Ingi": {
      "shifts": [
        {
          "date": "2026-07-01",
          "start": "13:00",
          "end": "17:00",
          "role": "Sameiginleg vakt",
          "shared": true,
          "parent": "Allir foreldrar"
        },
        {
          "date": "2026-07-01",
          "start": "17:00",
          "end": "21:00",
          "role": "Foreldravakt",
          "parent": "Inga og Björn"
        },
        {
          "date": "2026-07-01",
          "start": "21:00",
          "end": "08:30",
          "endDate": "2026-07-02",
          "role": "Svefnstjóri",
          "parent": "Garðar / Ásta"
        },
        {
          "date": "2026-07-02",
          "start": "08:30",
          "end": "13:00",
          "role": "Foreldravakt",
          "parent": "Tómas og Hjördís"
        },
        {
          "date": "2026-07-02",
          "start": "13:00",
          "end": "17:00",
          "role": "Foreldravakt",
          "parent": "Valdís og Hanna"
        },
        {
          "date": "2026-07-02",
          "start": "17:00",
          "end": "21:00",
          "role": "Foreldravakt",
          "parent": "Ólöf"
        },
        {
          "date": "2026-07-02",
          "start": "21:00",
          "end": "08:30",
          "endDate": "2026-07-03",
          "role": "Svefnstjóri",
          "parent": "Kjartan / Natalie"
        },
        {
          "date": "2026-07-03",
          "start": "08:30",
          "end": "13:00",
          "role": "Foreldravakt",
          "parent": "Eva/Beitir"
        },
        {
          "date": "2026-07-03",
          "start": "13:00",
          "end": "17:00",
          "role": "Foreldravakt",
          "parent": "Björg og Tryggvi"
        },
        {
          "date": "2026-07-03",
          "start": "17:00",
          "end": "21:00",
          "role": "Foreldravakt",
          "parent": "Valdís og Hanna"
        },
        {
          "date": "2026-07-03",
          "start": "21:00",
          "end": "08:30",
          "endDate": "2026-07-04",
          "role": "Svefnstjóri",
          "parent": "Brynjólfur"
        },
        {
          "date": "2026-07-04",
          "start": "08:30",
          "end": "11:00",
          "role": "Foreldravakt",
          "parent": "Tómas og Hjördís"
        },
        {
          "date": "2026-07-04",
          "start": "11:00",
          "end": "15:00",
          "role": "Sameiginleg vakt",
          "shared": true,
          "parent": "Allir foreldrar"
        }
      ],
      "contact": {
        "role": "Tengiliður liðs",
        "parent": "Ásta"
      }
    }
  }
};
